apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: istio-system 
data:
  prometheus-alert-rules.yml: |
    groups:
    - name: NodeResourceAlerts
      rules:
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Memory Usage
          description: "Node memory usage is above 80% for more than 5 minutes."
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU Usage
          description: "CPU usage is above 80% for more than 5 minutes."
