version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
    volumes:
      - .:/app 

  db:
    image: postgres:latest 
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
